### ISSUE TITLE
Rbac-manager repeatedly creates and deletes service account

### ISSUE THREAD

**Issue by thejosephstevens** [FairwindsOps/rbac-manager#110]
I ran into an issue earlier today where I was deploying a new log collector with a basic service account bound to one cluster role and after I launched the RBACDefinition rbac-manager started to repeatedly create and delete the same Service account
```
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Deleting Service Account zlog-collector"
time="2019-12-30T19:22:18Z" level=info msg="Creating Service Account: zlog-collector"
```
(this is a snippet, it was doing that endlessly from when I deployed the definition to when I deleted it)

My setup was this:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zlog-collector
  namespace: zlog
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - deployments
  - pods
  - events
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: zlog-collector
rbacBindings:
  - name: zlog-collector
    subjects:
      - kind: ServiceAccount
        name: zlog-collector
        namespace: zlog
    clusterRoleBindings:
      - namespace: zlog
        clusterRole: zlog-collector
```

Any ideas? Tagging @sudermanjr since you seem to run point on these.
