### ISSUE TITLE
Enable mulitple namespaces under one clusterRole

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#111]
I have a query and just want to know if that is doable with rbac-manager ?

 **Case1** - Is it possible to define multiple namespaces under one cluster role
 
 I know below config is doable
 
       - kind: User
        name: bloomreach-bre-deploy-user
    roleBindings:
      - clusterRole: admin
        namespace: namespace1
      - clusterRole: admin
        namespace: namespace2

But is it possible to define like below?

       - kind: User
        name: bloomreach-bre-deploy-user
    roleBindings:
      - clusterRole: admin
        namespace: namespace1
        namespace: namespace2
        namespace: namespace3

**Comment by sudermanjr** [comment]
@VarunTyagi86 Thanks for the question. 

The second example that your are looking for is not possible. You would have to do a list like your first example.

The other option is to do namespace selectors based on labels:

```
    roleBindings:
      - clusterRole: edit
        namespaceSelector:
          matchLabels:
            ci: edit
```

That might simplify your definition, but then you will have to label the namespaces appropriately.

This behavior is documented [here](https://github.com/FairwindsOps/rbac-manager/blob/master/docs/rbacdefinitions.md)

**Comment by VarunTyagi86** [comment]
Thank you Andrew !! 

What you mentioned i am aware of the same and we are using that. But is it possible to add this feature , it will make the configuratioin file much more simple, also make the operations simpler.

**Comment by sudermanjr** [comment]
I don't see us supporting this in the near future, as it would require a change to the underlying CRD. The exact yaml you specified is not possible due to multiple keys being named the same. We would have to do something like:

```
roleBindings:
  - clusterRole: admin
    namespaces:
      - namespace1
      - namespace2
```

This would be a very significant change and is of relatively low benefit, since the functionality already exists.
