### ISSUE TITLE
Not running in OpenShift

### ISSUE THREAD

**Issue by bsctl** [FairwindsOps/rbac-manager#126]
We deployed rbac-manager in OpenShift OKD 3.11. When starting the operator, OpenShift complains about user nobody in the Dockerfile.

`Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root`

We fixed this by replacing `USER nobody` with `USER 65534` and commenting `runAsUser: 1200` in the manifest file

```yaml
          ...
          securityContext:
          #runAsUser: 1200
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
```
in the `deploy/all.yaml` file.
