### ISSUE TITLE
Question about using active directory account with rbac manager

### ISSUE THREAD

**Issue by slaurencelle** [FairwindsOps/rbac-manager#157]
Hello,

i want to be able to restrcit the access to my kubernetes cluster using rbac-manager to manage the account use on my Microsoft Active Directory. 
How can i do that ?

Tks in advance

Stephane

**Comment by sudermanjr** [comment]
I'm not super familiar with Active directory directly, but the way it works for both Google and EKS are similar.

Generally, you just reference the username in the rbac definition. So from the basic example in the readme:

```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: joe-access
rbacBindings:
  - name: joe
    subjects:
      - kind: User
        name: joe@example.com
    roleBindings:
      - namespace: api
        clusterRole: view
      - namespace: web
        clusterRole: edit
```

You can replace the subject `joe@example.com` with your active directory usernames.

Another possibility is that you map active directory users with kubernetes groups, then the subject becomes `kind: Group` and the group name is the `name`
