### ISSUE TITLE
Yaml validation error on matchExpressions

### ISSUE THREAD

**Issue by reggie-k** [FairwindsOps/rbac-manager#182]
Trying to apply an RBACDefinition CR with    matchExpressions. 
```
  roleBindings:
     - clusterRole: edit
       namespaceSelector:
           matchExpressions:
		- {key: kuku, operator: Exists}
```
The error received is:
Error parsing YAML: YAMLException: end of the stream or a document separator is expected at line 25, column 11:
- {key: kuku, operator: Exists}

Is it possible the CRD lacks the items stanza under matchExpressions array..?
