### ISSUE TITLE
Image tag in manifests is incorrect for v0.10.0 and v0.9.4

### ISSUE THREAD

**Issue by tsde** [FairwindsOps/rbac-manager#191]
Hello,

I use kustomize to deploy rbac-manager as I wanted to give it a try. I came up with a pretty simple kustomization file referencing all the manifests available in the deploy directory:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/FairwindsOps/rbac-manager/v0.10.0/deploy/0_namespace.yaml
- https://raw.githubusercontent.com/FairwindsOps/rbac-manager/v0.10.0/deploy/1_rbac.yaml
- https://raw.githubusercontent.com/FairwindsOps/rbac-manager/v0.10.0/deploy/2_crd.yaml
- https://raw.githubusercontent.com/FairwindsOps/rbac-manager/v0.10.0/deploy/3_deployment.yaml
```

After deploying, I noticed that the rbac-manager pod entered in a `CrashLoopBackOff` state as the readiness/liveness probes targeting port 8042 couldn't retrieve a proper status. I then found out that the image tag used in `3_deployment.yaml` incorrectly point to v0.9.4 instead of v0.10.0: https://github.com/FairwindsOps/rbac-manager/blob/v0.10.0/deploy/3_deployment.yaml#L23

I also found out that the same applies for v0.9.4 `all.yaml` manifest which uses v0.9.3 as image tag: https://github.com/FairwindsOps/rbac-manager/blob/v0.9.4/deploy/all.yaml#L161

Apparently, image tag was fixed in https://github.com/FairwindsOps/rbac-manager/commit/9c839481675407fd26633d723e6cac659c381c41 for v0.9.4 and in https://github.com/FairwindsOps/rbac-manager/commit/32e35b6100153f441a923e5f9b2abde3e0c741fe for v0.10.0 but the git tags don't include these commits.

Is it possible to fix at least the v0.10.0 tag ? Is there a reason for not "promoting" this tag as a release like previous tags ?

Notice that v0.9.4 manifest is still usable even though is uses the v0.9.3 image as there wasn't any port change for /metrics so liveness/readiness probes are working. That's how I could finally test rbac-manager and I can tell that you did a pretty good job with this operator. It really helps so thank you for that.
