### ISSUE TITLE
Question on multi-tenant cluster use case - dynamic subject

### ISSUE THREAD

**Issue by tebo-ernstberger** [FairwindsOps/rbac-manager#215]
Hello,

Thanks for creating this tool. It looks great so far. 
Is there a way to dynamically set the subject(s) from a namespace label/annotation?

Context: We have a lot of multi-tenant clusters and we keep track of each namespace owner "Group" via an annotation on the namespace. 

For example
```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: dev-access
rbacBindings:
  - name: dev-team
    subjects:
      - kind: Group
        name: {{ Value from a matching namespace label or annotation }}
    roleBindings:
      - clusterRole: edit
        namespaceSelector:
          matchLabels:
            developerRBAC: true
```

I didn't see anything about this in the documentation. But just so I know, is it something you would accept a PR for? And also what would be the level of effort?

Thank you in advance,
