### ISSUE TITLE
Scoped naming like "yolt:scoped:name" not allowed (due to RFC 1123 domain validation)

### ISSUE THREAD

**Issue by andrejvanderzee** [FairwindsOps/rbac-manager#230]
We scope our ClusterRoles with `yolt:scope:` but we get the following error: 

```
$ kubectl apply -f /tmp/fail.yml
`The RBACDefinition "yolt:scoped:name" is invalid: metadata.name: Invalid value: "yolt:scoped:name": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')``
```

Below our resource definition:

```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: yolt:scoped:name
rbacBindings:
- name: cluster-admin
  subjects:
  - kind: User
    name: jane@example.com
  clusterRoleBindings:
  - clusterRole: cluster-admin
```

**Comment by sudermanjr** [comment]
You cannot name the the rbac-definition that way because it is a kubernetes API object. Thus the RFC1123 error.

You will want to put that name inside the `clusterRole` field, not the `metadata.name` field.


```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: something-rfc-1123-compliant
rbacBindings:
- name: cluster-admin
  subjects:
  - kind: User
    name: jane@example.com
  clusterRoleBindings:
  - clusterRole: yolt:scoped:name
  ```
