### ISSUE TITLE
ValidationError(RBACDefinition.rbacBindings[0].subjects[0]): unknown field "automountServiceAccountToken"

### ISSUE THREAD

**Issue by scholz-afis** [FairwindsOps/rbac-manager#370]
### What happened?

`kubectl -n users apply -f users_scholz_rbacdefinition.yml` returns with an error:
```
error: error validating "users_scholz_rbacdefinition.yml": error validating data: ValidationError(RBACDefinition.rbacBindings[0].subjects[0]): unknown field "automountServiceAccountToken" in io.reactiveops.rbacmanager.v1beta1.RBACDefinition.rbacBindings.subjects; if you choose to ignore these errors, turn validation off with --validate=false
```

### What did you expect to happen?

rbc-manager's API accepts field `automountServiceAccountToken` as written in e.g. `https://github.com/FairwindsOps/rbac-manager/blob/master/examples/rbacdefinition-everything.yaml`.

### How can we reproduce this?

File content of `users_scholz_rbacdefinition.yml`:
```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: scholz-rbacdefinition
  namespace: default
rbacBindings:
  - name: scholz-rbacbindings
    subjects:
      - kind: ServiceAccount
        name: scholz
        namespace: users
        automountServiceAccountToken: false
```

Execute:
```
kubectl create namespace users
kubectl -n users apply -f users_scholz_rbacdefinition.yml
```

### Version

https://charts.fairwinds.com/stable targetRevision: 1.15.2 => "rbac-manager 1.4.2 running"

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
