### ISSUE TITLE
Need help for implementing this in my scenario.

### ISSUE THREAD

**Issue by asabhi6776** [FairwindsOps/rbac-manager#396]
Hi, 

I need to provide access to one of developer, he need full access to only one namespace and rest other namespaces he need readonly access. Please help me how to do that. 
In example definitions i only got option to select namespaces based on labels, is there any other way to achieve above.

Thanks in advance.

**Comment by sudermanjr** [comment]
Hi! Happy to help. That should definitely be possible. Here's an example that gets you close to what you need. This may need to be tweaked based on how you are authenticating. This example uses the kind `Group`, because we use aws iam auth, which assigns people to groups. However, you should be able to modify that to user with no issues.


```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: read-everywhere-admin-single-namespace
  namespace: rbac-manager
rbacBindings:
- name: team1
  subjects:
  - kind: Group
    name: team1
  clusterRoleBindings:
  - clusterRole: view
  roleBindings:
  - clusterRole: edit
    namespace: example-namespace
```

This gives the clusterRoleBinding `view` to the users in Group team1, and the roleBinding `edit` to the users in group team1 in the namespace example-namespace.

The trick here is giving a `roleBinding` in a specific namespace. That rolebinding could be any role (such as cluster-admin), and because it is namespaced, it will only apply to that named namespace
