### ISSUE TITLE
ClusterRoleBindings doesn't get created when no subject is set

### ISSUE THREAD

**Issue by joschi36** [FairwindsOps/rbac-manager#79]
In my cluster no ClusterRoleBindings are getting created by rbac-manager when no subject is set.
Also no error is outputted.

**RBAC Definition (redacted)**
```yaml
- name: XXX-admins
  subjects:
    - kind: User
      name: 'XXX/john.doe@example.com'
  clusterRoleBindings:
    - clusterRole: cluster-admin
- name: YYY-admins
  subjects:
    - kind: User
      name: 'XXX/jane.doe@example.com'
    - kind: User
      name: 'XXX/sterling.archer@example.com'
  clusterRoleBindings:
    - clusterRole: XXX:customer-admin
  roleBindings:
    - clusterRole: admin
      namespaceSelector:
        matchExpressions:
          - key: customer-system
            operator: NotIn
            values:
              - "true"
- name: ZZZ-users
  subjects: []
  roleBindings:
    - clusterRole: admin
      namespaceSelector:
        matchExpressions:
          - key: customer-system
            operator: NotIn
            values:
              - "true"
```

**Role Bindings**
```
default       XXX-users-YYY-admins-admin   ClusterRole/admin      XXX/jane.doe@example.com, XXX/sterling.archer@example.com
default       XXX-users-YYY-users-admin    ClusterRole/admin                                                               
kube-public   XXX-users-YYY-admins-admin   ClusterRole/admin      XXX/jane.doe@example.com, XXX/sterling.archer@example.com
kube-public   XXX-users-YYY-users-admin    ClusterRole/admin                                                               
test          XXX-users-YYY-admins-admin   ClusterRole/admin      XXX/jane.doe@example.com, XXX/sterling.archer@example.com
test          XXX-users-YYY-users-admin    ClusterRole/admin                                                               
```

**Cluster Role Bindings**
No ClusterRoleBindings getting created

**Log**
```
time="2019-09-16T15:45:59Z" level=info msg=----------------------------------
time="2019-09-16T15:45:59Z" level=info msg="rbac-manager 0.8.2 running"
time="2019-09-16T15:45:59Z" level=info msg=----------------------------------
time="2019-09-16T15:45:59Z" level=info msg="Registering components"
time="2019-09-16T15:45:59Z" level=info msg="Watching resources related to RBAC Definitions"
time="2019-09-16T15:45:59Z" level=info msg="Watching RBAC Definitions"
time="2019-09-16T15:45:59Z" level=info msg="Reconciling RBACDefinition XXX-users"
time="2019-09-16T15:45:59Z" level=info msg="Reconciling default namespace for XXX-users"
time="2019-09-16T15:45:59Z" level=info msg="Reconciling kube-public namespace for XXX-users"
time="2019-09-16T15:45:59Z" level=info msg="Reconciling kube-system namespace for XXX-users"
time="2019-09-16T15:45:59Z" level=info msg="Reconciling monitoring namespace for XXX-users"
time="2019-09-16T15:46:00Z" level=info msg="Reconciling rbac-manager namespace for XXX-users"
time="2019-09-16T15:46:00Z" level=info msg="Reconciling test namespace for XXX-users"
time="2019-09-16T15:46:00Z" level=info msg="Reconciling cert-manager namespace for XXX-users"
```
