### ISSUE TITLE
Verify behavior around pre-existing service accounts

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/rbac-manager#84]
We don't currently have a known pattern around how to handle pre-existing service accounts. We should test what happens and decide on a defined policy.

**Comment by sudermanjr** [comment]
reported by @thejosephstevens

**Comment by thejosephstevens** [comment]
Hey all! The super quick feedback I'd give on the functionality here is, as a consumer I don't actually much care what the outcome is as long as it's in the docs. Part of the reason I landed in this spot is the existing documentation talks at length about generating all of the bindings at runtime, but it doesn't actually mention (unless I missed a section) anything about management of the subjects. Since there was no reference I assume it was BYO, and that turned out to work for our original installs. It also seemed to follow from the notion that it would set up bindings with other resources (like groups) that don't have a visible kube resource backing them.

FWIW, the spec I was running when I ran into my issues was this:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labeler
  namespace: infra
imagePullSecrets:
 - name: image-pull-creds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: node-labeler
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "patch"]
---
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: node-labeler
rbacBindings:
  - name: node-labeler
    subjects:
      - kind: ServiceAccount
        name: node-labeler
    clusterRoleBindings:
      - namespace: infra
        clusterRole: node-labeler
```

With this config, rbac-manager logged errors on creating the service account due to missing namespace (prior to investigation of this, it was hooking up to an existing SA just fine, so it may have been throwing an error without me noticing).
